# Generated by Django 4.2 on 2023-05-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_photo', models.ImageField(upload_to='hostels/', verbose_name='')),
                ('price_for_scholarship', models.IntegerField(verbose_name='')),
                ('price_for_paid_basis', models.IntegerField(verbose_name='')),
                ('floors', models.IntegerField(verbose_name='')),
                ('gym', models.BooleanField(default=False, verbose_name='')),
                ('type', models.CharField(max_length=128, verbose_name='')),
                ('coworking', models.BooleanField(default=False, verbose_name='')),
                ('kitchens', models.TextField(verbose_name='')),
                ('washers', models.TextField(verbose_name='')),
                ('adress', models.TextField(verbose_name='')),
                ('dryers', models.IntegerField(verbose_name='')),
                ('to_pryaniki', models.CharField(max_length=64, verbose_name='')),
                ('to_pk', models.CharField(max_length=64, verbose_name='')),
                ('to_bs', models.CharField(max_length=64, verbose_name='')),
                ('to_mikhalka', models.CharField(max_length=64, verbose_name='')),
                ('to_avtovaz', models.CharField(max_length=64, verbose_name='')),
            ],
        ),
    ]
