# Generated by Django 4.2 on 2023-05-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='adress',
            field=models.CharField(max_length=256, verbose_name='Adress'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='coworking',
            field=models.BooleanField(default=False, verbose_name='Coworking'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='dryers',
            field=models.IntegerField(verbose_name='Dryers'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='floors',
            field=models.IntegerField(verbose_name='Floors'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='gym',
            field=models.BooleanField(default=False, verbose_name='Gym'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_photo',
            field=models.ImageField(upload_to='hostels/', verbose_name='Hostel Photo'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='kitchens',
            field=models.CharField(max_length=32, verbose_name='Kitchens'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='price_for_paid_basis',
            field=models.IntegerField(verbose_name='Price for paid basis'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='price_for_scholarship',
            field=models.IntegerField(verbose_name='Price For Scholarship'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='to_avtovaz',
            field=models.CharField(max_length=64, verbose_name='To Avtovaz'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='to_bs',
            field=models.CharField(max_length=64, verbose_name='To BS'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='to_mikhalka',
            field=models.CharField(max_length=64, verbose_name='To Mikhalka'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='to_pk',
            field=models.CharField(max_length=64, verbose_name='To PK'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='to_pryaniki',
            field=models.CharField(max_length=64, verbose_name='To Pryaniki'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='type',
            field=models.CharField(max_length=128, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='washers',
            field=models.CharField(max_length=32, verbose_name='Washers'),
        ),
    ]
