# Generated by Django 4.2 on 2023-05-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_alter_hostel_adress_alter_hostel_coworking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='adress',
            field=models.CharField(max_length=256, verbose_name='Address'),
        ),
    ]
