# Generated by Django 4.2 on 2023-05-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0003_alter_hostel_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='hostel_number',
            field=models.CharField(default=0, max_length=2, verbose_name='Hostel Number'),
            preserve_default=False,
        ),
    ]
