# Generated by Django 4.2 on 2023-05-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='lesson_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
