# Generated by Django 4.2 on 2023-05-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0002_pair_lesson_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='group',
            field=models.CharField(default=-104, max_length=64),
            preserve_default=False,
        ),
    ]
