# Generated by Django 4.2 on 2023-05-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0003_pair_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='location',
            field=models.CharField(max_length=512),
        ),
    ]
