# Generated by Django 4.2 on 2023-05-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0004_alter_pair_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='sbj',
            field=models.CharField(max_length=512),
        ),
    ]
