# Generated by Django 4.2 on 2023-05-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_auth', '0002_customuser_is_proforg_customuser_is_starosta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
